name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Proto:
    runs-on: ubuntu-latest   
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2        
        with: 
          repository: beerproto/beerproto
          path: proto
      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - name: Build go 
        run:  protoc -I=$GITHUB_WORKSPACE/proto --go_out=. beer.proto
      - name: Move files 
        run:  mv github.com/beerproto/beerproto.go/beer.pb.go .
      - name: Cleanup
        run:  rm -r github.com/             
      - name: Git Commit on Workflow
        uses: matheusalbino/git-commit@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: Updating Protocol Documentation 

