name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Proto:
    runs-on: ubuntu-latest   
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2        
        with: 
          repository: beerproto/beerproto
          path: proto
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - name: Install Go Plugin for Protoc
        run: go install github.com/golang/protobuf/protoc-gen-go
      - name: Build go 
        run:  protoc -I=$GITHUB_WORKSPACE/proto --go_out=. beer.proto
      - name: Cleanup
        run:  rm -r proto             
      - name: Git Commit on Workflow
        uses: matheusalbino/git-commit@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: Updating beer.pb.go 

